{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Exception Handling\n",
    "___\n",
    "\n",
    "+ In Short, MUST throw your own error\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "##  Exception Handling\n",
    "\n",
    "Here we talking about run time errors, i.e Errors which are caused by the user\n",
    "\n",
    "Not Logical (tested using debugger) or Syntax (tested using compiler)\n",
    "\n",
    "Pupose of Exceptions: **To give proper Error messages to the user**\n",
    "\n",
    "c++ does **NOT** have a mechanism to throw an exeption, we have to not only throw it **ourselves**, but also **CHECK** for the error as well, to know when to throw the error.\n",
    "\n",
    "```\n",
    "if (b==0)\n",
    "   throw 1;\n",
    "\n",
    "```\n",
    "\n",
    "But the reason why it works this way (***where you need to check and throw the error yourself***), e.g. \n",
    "\n",
    "I have a **division function**, that needs to perform division, but lets say you pass a zero, to divide by\n",
    "\n",
    "Then its the purpose of the division function to **throw error**, NOT Return Error, to the calling function:\n",
    "\n",
    "```\n",
    "\n",
    "int division (int x, int y){\n",
    "    if (y==0)\n",
    "        throw 1;\n",
    "    }\n",
    "    return x/y;\n",
    "```\n",
    "\n",
    "And since we throwing an **int**, we need to define to define the catch as **int**:\n",
    "\n",
    "```\n",
    "catch(int e){\n",
    "    ...\n",
    "}\n",
    "\n",
    "```\n",
    "So the link is **throw** and **catch**, and the **1** we use to throw it will be the **e** value\n",
    "\n",
    "\n",
    "### Variations of Exeption Handling\n",
    "___\n",
    "\n",
    "#### Multiple throw value and catch blocks\n",
    "\n",
    "Previously we throw int value. Can we throw float, double, char, string, ect? Yes, can throw anything.\n",
    "\n",
    "We can even throw our own class:\n",
    "\n",
    "```\n",
    "class MyException{}\n",
    "\n",
    "if (b==)\n",
    "    throw MyException();\n",
    "\n",
    "```\n",
    "And you can or dont have to inherit from exception, e.g:\n",
    "\n",
    "```\n",
    "class MyException: public exception\n",
    "\n",
    "```\n",
    "\n",
    "Also the function that you declaring, you can define in the signature that the function is throwing it in its signature:\n",
    "\n",
    "```\n",
    "int division (int x, int y) throw (MyException) {\n",
    "\n",
    "    if (b==)\n",
    "        throw MyException;\n",
    "    }\n",
    "\n",
    "}\n",
    "```\n",
    "\n",
    "\n",
    "or thowing an int then \n",
    "\n",
    "```\n",
    "int division (int x, int y) throw (int) {\n",
    "\n",
    "    if (b==0)\n",
    "        throw 1;\n",
    "    }\n",
    "\n",
    "}\n",
    "```\n",
    "\n",
    "But the signature in the function definition is not mandatory, its just some information to calling program to show that this function wil throw the type of errors in throw signature.\n",
    "\n",
    "But then we need to check for it?\n",
    "\n",
    "But it we have the following, that means this function does not throw exception, as the throw is empty:\n",
    "\n",
    "```\n",
    "int division (int x, int y) throw () {\n",
    "\n",
    "    return x/y\n",
    "\n",
    "```\n",
    "\n",
    "\n",
    "#### Catch \"ALL\" \n",
    "\n",
    "```\n",
    "catch(...){\n",
    "    cout<<\"Some Error Occurred\"<<\"endl;\n",
    "}\n",
    "\n",
    "```\n",
    "\n",
    "But ```catch(...)``` must be the **last** catch block\n",
    "\n",
    "We can also have nested try/catch inside each other\n",
    "\n",
    "\n",
    "Where we inherit Execeptions the flow has to be from Child to Parent, i.e Parent has to be defined last:\n",
    "\n",
    "```\n",
    "class Exception1{}\n",
    "\n",
    "class Exception2: public Exception1{}\n",
    "\n",
    "try{\n",
    "...\n",
    "}\n",
    "catch (Exception2 e){}\n",
    "catch (Exception1 e){}\n",
    "```\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#include <iostream>\n",
    "#include <climits>\n",
    "#include <math.h>\n",
    "using namespace std;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Division by Zero (int)--Error code:1\n",
      "Bye\n"
     ]
    }
   ],
   "source": [
    "int a=10; \n",
    "int b=0; \n",
    "int c;\n",
    "\n",
    "try{\n",
    "    if (b==0)\n",
    "        throw 1;\n",
    "    c = a/b;\n",
    "    cout<<c<<endl;\n",
    "}\n",
    "catch(int e){\n",
    "    cout<<\"Division by Zero (int)\"<<\"--Error code:\"<<e<<endl;\n",
    "}\n",
    "catch(float e){\n",
    "    cout<<\"Division by Zero (float)\"<<\"--Error code:\"<<e<<endl;\n",
    "}\n",
    "catch(double e){\n",
    "    cout<<\"Division by Zero (double)\"<<\"--Error code:\"<<e<<endl;\n",
    "}\n",
    "catch(char e){\n",
    "    cout<<\"Division by Zero (char)\"<<\"--Error code:\"<<e<<endl;\n",
    "}\n",
    "catch(string e){\n",
    "    cout<<\"Division by Zero (string)\"<<\"--Error code:\"<<e<<endl;\n",
    "}\n",
    "// catch(...){\n",
    "//     cout<<\"Some Error Occurred\"<<\"endl;\n",
    "// }\n",
    "cout<<\"Bye\"<<endl;"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "C++17",
   "language": "C++17",
   "name": "xcpp17"
  },
  "language_info": {
   "codemirror_mode": "text/x-c++src",
   "file_extension": ".cpp",
   "mimetype": "text/x-c++src",
   "name": "c++",
   "version": "-std=c++17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
